version: '3.9'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  ipfs:
    image: ipfs/go-ipfs:latest
    restart: unless-stopped
    ports:
      - '5001:5001' # API
      - '8080:8080' # Gateway
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - env.example
    depends_on:
      - mongo
      - ipfs
volumes:
  mongo-data:
  ipfs_staging:
  ipfs_data: 